apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    {{- include "catalogue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "catalogue.selectorLabels" . | nindent 4 }}
